
[Config]
	#For first time setup make sure you launch minecraft with this link: https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?access_type=offline&approval_prompt=force&client_id=67117034265-fpgd27545uvujcgpqcma6b99o0bph26j.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2FCallback&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&service=lso&o2v=1&theme=glif&flowName=GeneralOAuthFlow 
	# Once the loading process stops for a sec login and accept required scopes
	# If you want to change account delete the StoredCredential file in tokens
	#If you have worlds set to upload make sure you quit to main menu and allow CC time to upload your file. 
	#If your game crashes all worlds configured to auto save will stop doing so until you re-enable them!
	#
	#
	#
	#Do you want to enable cc on launch? (true/false)
	ccEnabled = false
	#Don't recommend to set to more than 5 if you have multiple worlds being saved or if you're too deep into the game
	#Check google drive space if you're worried
	"Max Backups" = 5
	#Match array positions for each world file and complete all req for each property 
	#Make sure to put a comma between each field ex: '',''
	#Copy paste world path 
	"World Paths" = []
	#World name in google drive MAKE SURE THIS IS DIFFERENT FOR EACH SAVED WORLD 
	#Does not need to be the same as the actual world name in minercaft
	"World Names" = []
	#Do you want this file to be uploaded and downloaded using CC 
	#true/false
	"World Status" = []
	#DO NOT EDIT THIS. It's used to ensure that files are not overridden.
	"Most recent crash" = ""

